### ISSUE TITLE
PRCP_Discharge data

### ISSUE THREAD

**Issue by GabiZuccolotto** [hydro-lab/groundwater#12]
GPM precipitation trends do not relate well to discharge data (see attached plot) 
Possible that accumulated precipitation across the entire basin may not be best to use. 

<img width="875" alt="lowerlimpopo_hyetograph_example" src="https://github.com/hydro-lab/groundwater/assets/78925157/3b00a8b5-544d-4812-8793-761cf3eb5f57">

**Comment by GabiZuccolotto** [comment]
I tried redownloading the Giovanni data using a smaller bounding box around the lower Limpopo sub-basin rather than the entire LRB. Still not great response (see attached plot). Should discuss next steps. 

<img width="875" alt="lowerlimpopo_hyetograph_example_2" src="https://github.com/hydro-lab/groundwater/assets/78925157/849a2111-466b-4476-ac17-8fedcb5790f2">

**Comment by dmkahler** [comment]
Are these daily data?  Over the entire basin, I wouldn't expect to be able to see any correlation except by hydrologic year.

**Comment by GabiZuccolotto** [comment]
Good catch. New plots below. 
<img width="879" alt="hydroyear_rainfall_runoff" src="https://github.com/hydro-lab/groundwater/assets/78925157/d785ae4c-6112-4ca3-b135-6980152da4df">

**Comment by GabiZuccolotto** [comment]
Correlation plots between annual water height and PRCP for each gauge
<img width="467" alt="chokwe_PRCP_corr" src="https://github.com/hydro-lab/groundwater/assets/78925157/21963866-6863-42e2-8750-304a4b9c04bc">
<img width="467" alt="XaiXai_PRCP_corr" src="https://github.com/hydro-lab/groundwater/assets/78925157/bd6785ab-08fe-43c6-bff6-b3ac274bcdb3">

**Comment by dmkahler** [comment]
Well, the analysis looks good, but I'm not sure I see a clear answer to our question.  Let's think about potential further analysis.
